---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %> 
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: amazon-2013.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-3be4bc52
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: amazon-2014.03
  driver_plugin: ec2
  driver_config:
    image_id: ami-6b726502
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: suse-11.3
  driver_plugin: ec2
  driver_config:
    image_id: ami-e8084981
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: fedora-20
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: debian-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: ubuntu-10.04
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb

suites:

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  attributes: {}

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  attributes: {}

#- name: service_systemd
#  run_list:
#  - recipe[chef-client::systemd_service]
#  attributes: {}
#  includes: ["centos-7.0", "fedora-20", "debian-7.0"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-10.04", "ubuntu-12.04", "ubuntu-14.04"]
  attributes: {}

- name: cron
  run_list:
  - recipe[chef-client::cron]
  attributes: {}

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
  attributes: {}

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
